/** Shared storefront UI: navigation, cards, reveals, notifications, newsletter, and utilities. */
(function(){'use strict';
 const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
 function toast(message){let region=document.querySelector('.toast-region');if(!region){region=document.createElement('div');region.className='toast-region';region.setAttribute('aria-live','polite');document.body.append(region);}const item=document.createElement('div');item.className='toast';item.textContent=message;region.append(item);setTimeout(()=>item.remove(),2800);}
 function card(product){const saved=window.Wishlist?.has(product.id);return `<article class="product-card" data-product-id="${product.id}"><div class="product-card__media"><a href="product.html?id=${product.id}" aria-label="View ${product.name}"><img src="${product.images?.[0]||StoreDB.placeholder(product.name)}" alt="${product.name}" loading="lazy"></a>${product.badge?`<span class="product-card__badge">${product.badge}</span>`:''}<button class="icon-button product-card__wishlist" type="button" aria-label="${saved?'Remove from':'Add to'} wishlist" data-wishlist-toggle="${product.id}">${saved?'♥':'♡'}</button><div class="product-card__actions"><a class="button button--outline" href="product.html?id=${product.id}">Quick view</a><button class="button" type="button" data-add-cart="${product.id}">Add</button></div></div><div class="product-card__body"><div class="product-card__meta"><span>${product.category}</span><span>${money(product.price)}</span></div><h3 class="product-card__title"><a href="product.html?id=${product.id}">${product.name}</a></h3></div></article>`;}
 function initHeader(){const toggle=document.querySelector('[data-menu-toggle]'),drawer=document.querySelector('[data-mobile-navigation]'),backdrop=document.querySelector('[data-drawer-backdrop]');const close=()=>{drawer?.classList.remove('is-open');backdrop?.classList.remove('is-open');document.body.classList.remove('menu-open');toggle?.setAttribute('aria-expanded','false');drawer?.setAttribute('aria-hidden','true');};toggle?.addEventListener('click',()=>{drawer?.classList.add('is-open');backdrop?.classList.add('is-open');document.body.classList.add('menu-open');toggle.setAttribute('aria-expanded','true');drawer?.setAttribute('aria-hidden','false');});document.querySelector('[data-menu-close]')?.addEventListener('click',close);backdrop?.addEventListener('click',close);document.querySelector('[data-dismiss-announcement]')?.addEventListener('click',e=>e.currentTarget.parentElement.remove());const search=document.querySelector('[data-search-panel]');document.querySelector('[data-search-toggle]')?.addEventListener('click',e=>{search?.classList.add('is-open');search?.setAttribute('aria-hidden','false');e.currentTarget.setAttribute('aria-expanded','true');search?.querySelector('input')?.focus();});document.querySelector('[data-search-close]')?.addEventListener('click',()=>{search?.classList.remove('is-open');search?.setAttribute('aria-hidden','true');});}
 function initCommon(){document.querySelector('[data-current-year]')?.replaceChildren(String(new Date().getFullYear()));const top=document.querySelector('[data-back-to-top]');addEventListener('scroll',()=>top?.classList.toggle('is-visible',scrollY>600),{passive:true});top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('is-revealed')),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));document.querySelectorAll('.button').forEach(button=>button.addEventListener('click',e=>{const r=document.createElement('span');r.className='ripple';r.style.left=`${e.offsetX-10}px`;r.style.top=`${e.offsetY-10}px`;button.append(r);setTimeout(()=>r.remove(),650);}));}
 function initProducts(){const root=document.querySelector('[data-featured-products]');if(root){root.innerHTML=StoreDB.getProducts().filter(p=>p.featured).slice(0,4).map(card).join('');root.setAttribute('aria-busy','false');}}
 function initActions(){document.addEventListener('click',e=>{const wish=e.target.closest('[data-wishlist-toggle]');if(wish){e.preventDefault();const active=Wishlist.toggle(wish.dataset.wishlistToggle);wish.textContent=active?'♥':'♡';wish.setAttribute('aria-label',`${active?'Remove from':'Add to'} wishlist`);}const add=e.target.closest('[data-add-cart]');if(add){e.preventDefault();Cart.add(add.dataset.addCart);}});document.querySelector('[data-newsletter-form]')?.addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('[data-newsletter-message]').textContent='Welcome to our private correspondence.';e.currentTarget.reset();});}
 window.StoreUI={money,toast,card};document.addEventListener('DOMContentLoaded',()=>{initHeader();initCommon();initProducts();initActions();});
})();

