/** LocalStorage data service. All persistence is isolated here so a future API can replace it. */
(function () {
  'use strict';
  const KEYS={products:'aurelia_products',cart:'aurelia_cart',wishlist:'aurelia_wishlist',settings:'aurelia_settings',orders:'aurelia_orders'};
  const placeholder=(label,tone='d8d1c5')=>`https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=85`;
  const DEFAULT_PRODUCTS=[
    {id:'p1',name:'Sculpted Wool Coat',price:890,description:'A double-faced wool coat shaped with architectural shoulders and a softly belted waist.',category:'Women',stock:12,sizes:['XS','S','M','L'],colors:['Camel','Black'],tags:['coat','wool','tailoring','new'],images:['https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?auto=format&fit=crop&w=1000&q=85'],featured:true,bestSelling:true,rating:4.9,badge:'New',createdAt:'2026-07-10'},
    {id:'p2',name:'Noir Draped Blazer',price:640,description:'Fluid Italian tailoring with a precise lapel, relaxed line, and satin-touch finish.',category:'Women',stock:8,sizes:['XS','S','M','L','XL'],colors:['Black','Ivory'],tags:['blazer','evening','tailoring'],images:['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=1000&q=85'],featured:true,bestSelling:false,rating:4.7,badge:'Exclusive',createdAt:'2026-07-06'},
    {id:'p3',name:'Atelier Cashmere Knit',price:420,description:'A quiet essential spun from exceptionally soft cashmere with a clean, relaxed silhouette.',category:'Men',stock:18,sizes:['S','M','L','XL'],colors:['Stone','Navy','Black'],tags:['knit','cashmere','essential'],images:['https://images.unsplash.com/photo-1610652492500-ded49ceeb378?auto=format&fit=crop&w=1000&q=85'],featured:true,bestSelling:true,rating:4.8,badge:'Bestseller',createdAt:'2026-06-28'},
    {id:'p4',name:'Form Leather Tote',price:780,description:'A structured everyday tote handcrafted from full-grain leather with a suede-lined interior.',category:'Accessories',stock:6,sizes:['One Size'],colors:['Espresso','Black','Burgundy'],tags:['bag','leather','tote'],images:['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1000&q=85'],featured:true,bestSelling:true,rating:4.9,badge:'Icon',createdAt:'2026-06-20'},
    {id:'p5',name:'Silk Column Dress',price:720,description:'Bias-cut silk falls in a long, luminous line finished with an asymmetric neckline.',category:'Women',stock:7,sizes:['XS','S','M','L'],colors:['Ivory','Black','Red'],tags:['dress','silk','evening'],images:['https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1000&q=85'],featured:false,bestSelling:true,rating:4.6,badge:'',createdAt:'2026-06-18'},
    {id:'p6',name:'Pleated Tailored Trouser',price:390,description:'High-rise tailored trousers with deep pleats and a generous straight leg.',category:'Men',stock:21,sizes:['28','30','32','34','36'],colors:['Charcoal','Black','Sand'],tags:['trouser','tailoring','formal'],images:['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=1000&q=85'],featured:false,bestSelling:false,rating:4.5,badge:'',createdAt:'2026-06-12'},
    {id:'p7',name:'Minimal Leather Loafer',price:560,description:'An understated loafer made in Italy with a hand-polished upper and tonal sole.',category:'Shoes',stock:14,sizes:['36','37','38','39','40','41','42'],colors:['Black','Oxblood'],tags:['shoe','leather','loafer'],images:['https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=85'],featured:false,bestSelling:true,rating:4.8,badge:'Bestseller',createdAt:'2026-06-01'},
    {id:'p8',name:'Élan Silk Scarf',price:230,description:'A hand-rolled silk twill scarf printed with the house geometric signature.',category:'Accessories',stock:25,sizes:['One Size'],colors:['Blue','Gold','Red'],tags:['scarf','silk','gift'],images:['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=1000&q=85'],featured:false,bestSelling:false,rating:4.4,badge:'Gift Edit',createdAt:'2026-05-24'}
  ];
  const read=(key,fallback=[])=>{try{const value=JSON.parse(localStorage.getItem(key));return value??fallback;}catch{return fallback;}};
  const write=(key,value)=>{localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new CustomEvent('aurelia:storage',{detail:{key,value}}));return value;};
  const seed=()=>{if(!localStorage.getItem(KEYS.products))write(KEYS.products,DEFAULT_PRODUCTS);};
  const makeId=()=>`p_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
  window.StoreDB={KEYS,seed,getProducts:()=>read(KEYS.products),getProduct:id=>read(KEYS.products).find(p=>p.id===id),saveProduct(product){const products=read(KEYS.products);const clean={...product,id:product.id||makeId(),updatedAt:new Date().toISOString()};const i=products.findIndex(p=>p.id===clean.id);i>=0?products.splice(i,1,clean):products.unshift({...clean,createdAt:new Date().toISOString()});write(KEYS.products,products);return clean;},deleteProduct(id){write(KEYS.products,read(KEYS.products).filter(p=>p.id!==id));},getCart:()=>read(KEYS.cart),setCart:v=>write(KEYS.cart,v),getWishlist:()=>read(KEYS.wishlist),setWishlist:v=>write(KEYS.wishlist,v),getSettings:()=>read(KEYS.settings,{}),setSettings:v=>write(KEYS.settings,v),getOrders:()=>read(KEYS.orders),addOrder:o=>write(KEYS.orders,[o,...read(KEYS.orders)]),resetProducts:()=>write(KEYS.products,DEFAULT_PRODUCTS),placeholder};
  seed();
})();

